---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx2-deployment
    labels:
      app: nginx
spec:
    replicas: 1
    selector:
     matchLabels:
       app: nginx
    template:
      metadata:
       labels:
          app: nginx
      spec:
       containers:
       - name: nginx
         image: 10.0.0.35:5000/nginx:v2
---
apiVersion: v1
kind: Service
metadata:
   name: ingress-nginx 
spec:
    selector:
        app: nginx
    type: NodePort
    ports:
      - port : 443
        targetPort: 80
        nodePort: 30066

